version: '3.8'

services:
  backend:
    image: aryantk10/seminar-hall-booking-backend:latest
    container_name: seminar-hall-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://aryantk1020:Timber2014*@cluster0.bk2olft.mongodb.net/seminar-hall-booking?retryWrites=true&w=majority&appName=Cluster0
      - NODE_ENV=development
      - PORT=5000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: aryantk10/seminar-hall-booking-frontend:latest
    container_name: seminar-hall-frontend
    ports:
      - "9002:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://seminar-hall-backend:5000/api
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: seminar-hall-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PROVISIONING_PATH=/etc/grafana/provisioning
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - app-network
    depends_on:
      - prometheus

networks:
  app-network:
    driver: bridge

volumes:
  grafana-storage: