services:
  - type: web
    name: seminar-hall-booking-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node dist/app.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://aryantk10:Aryan%40123@cluster0.bk2olft.mongodb.net/seminar-hall-booking?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://seminar-hall-booking-j69q.onrender.com
