global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['seminar-hall-backend:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['seminar-hall-prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 