global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['seminar-hall-prometheus:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['seminar-hall-backend:5000']
    metrics_path: '/metrics'

  - job_name: 'frontend'
    static_configs:
      - targets: ['seminar-hall-frontend:9002']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['seminar-hall-node-exporter:9100']