config:
  target: "http://localhost:5000"
  phases:
    - duration: 60
      arrivalRate: 5
      rampTo: 20
      name: "Warm up phase"
    - duration: 120
      arrivalRate: 20
      name: "Sustained load"
    - duration: 60
      arrivalRate: 20
      rampTo: 50
      name: "Stress test"

  defaults:
    headers:
      Content-Type: "application/json"

scenarios:
  - name: "Basic flow"
    flow:
      - get:
          url: "/health"
          expect:
            - statusCode: 200
      
      - get:
          url: "/api/halls"
          expect:
            - statusCode: 200

      - post:
          url: "/api/auth/login"
          json:
            email: "test@example.com"
            password: "testpassword123"
          capture:
            - json: "$.token"
              as: "authToken"
          expect:
            - statusCode: 200

      - get:
          url: "/api/bookings"
          headers:
            Authorization: "Bearer {{ authToken }}"
          expect:
            - statusCode: 200

  - name: "Search and filter"
    flow:
      - get:
          url: "/api/halls?capacity=50&date=2024-03-20"
          expect:
            - statusCode: 200

      - get:
          url: "/api/halls?available=true"
          expect:
            - statusCode: 200

# Performance thresholds
expect:
  # Response time thresholds
  - p95: 500  # 95% of requests should complete within 500ms
  - p99: 1000 # 99% of requests should complete within 1000ms
  
  # Error rate threshold
  - maxErrorRate: 5 # Maximum 5% error rate

# Metrics to track
metrics:
  - name: "response_time"
    unit: "ms"
  - name: "error_rate"
    unit: "%"
  - name: "requests_per_second"
    unit: "rps"
