name: Enhanced Slack Notifications

on:
  workflow_run:
    workflows:
      - "Main CI/CD Pipeline"
      - "Production Deployment"
      - "Basic Monitoring & Health Checks"
    types:
      - completed
      - requested
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      message:
        description: 'Custom notification message'
        required: true
        default: 'Manual test notification'
      severity:
        description: 'Notification severity'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - success
          - warning
          - error

jobs:
  # Job 1: Pipeline Start Notification
  pipeline-start:
    runs-on: ubuntu-latest
    name: Pipeline Start Notification
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
    - name: Send pipeline start notification
      run: |
        echo "🚀 Sending pipeline start notification..."
        
        # Determine trigger details
        if [[ "${{ github.event_name }}" == "push" ]]; then
          TRIGGER_TYPE="🔄 Push to ${{ github.ref_name }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"
        else
          TRIGGER_TYPE="🔀 Pull Request #${{ github.event.number }}"
          COMMIT_MSG="${{ github.event.pull_request.title }}"
        fi
        
        # Send Slack notification
        if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "🚀 *Seminar Hall Booking - CI/CD Pipeline Started*",
              "attachments": [
                {
                  "color": "#36a64f",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "🚀 CI/CD Pipeline Started"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Repository:*\n${{ github.repository }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Trigger:*\n'"$TRIGGER_TYPE"'"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Author:*\n${{ github.actor }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Commit:*\n`${{ github.sha }}`"
                        }
                      ]
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Message:* '"$COMMIT_MSG"'"
                      }
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "⏱️ Started at: <!date^$(date +%s)^{date_short_pretty} at {time}|$(date)>"
                        }
                      ]
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "👀 View Pipeline"
                          },
                          "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                          "style": "primary"
                        },
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "📝 View Commit"
                          },
                          "url": "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }} || echo "❌ Slack notification failed"
        else
          echo "⚠️ SLACK_WEBHOOK_URL not configured"
        fi

  # Job 2: Pipeline Completion Notification
  pipeline-complete:
    runs-on: ubuntu-latest
    name: Pipeline Completion Notification
    if: github.event_name == 'workflow_run'
    
    steps:
    - name: Determine pipeline status and details
      id: status
      run: |
        CONCLUSION="${{ github.event.workflow_run.conclusion }}"
        WORKFLOW_NAME="${{ github.event.workflow_run.name }}"
        RUN_URL="${{ github.event.workflow_run.html_url }}"
        
        case $CONCLUSION in
          "success")
            echo "status_emoji=✅" >> $GITHUB_OUTPUT
            echo "status_color=good" >> $GITHUB_OUTPUT
            echo "status_text=Success" >> $GITHUB_OUTPUT
            echo "status_message=Pipeline completed successfully! 🎉" >> $GITHUB_OUTPUT
            ;;
          "failure")
            echo "status_emoji=❌" >> $GITHUB_OUTPUT
            echo "status_color=danger" >> $GITHUB_OUTPUT
            echo "status_text=Failed" >> $GITHUB_OUTPUT
            echo "status_message=Pipeline failed! Please check the logs. 🚨" >> $GITHUB_OUTPUT
            ;;
          "cancelled")
            echo "status_emoji=⚠️" >> $GITHUB_OUTPUT
            echo "status_color=warning" >> $GITHUB_OUTPUT
            echo "status_text=Cancelled" >> $GITHUB_OUTPUT
            echo "status_message=Pipeline was cancelled. ⏹️" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "status_emoji=❓" >> $GITHUB_OUTPUT
            echo "status_color=#808080" >> $GITHUB_OUTPUT
            echo "status_text=Unknown" >> $GITHUB_OUTPUT
            echo "status_message=Pipeline status unknown. 🤔" >> $GITHUB_OUTPUT
            ;;
        esac
        
        echo "workflow_name=$WORKFLOW_NAME" >> $GITHUB_OUTPUT
        echo "conclusion=$CONCLUSION" >> $GITHUB_OUTPUT
        echo "run_url=$RUN_URL" >> $GITHUB_OUTPUT

    - name: Send pipeline completion notification
      run: |
        echo "📢 Sending pipeline completion notification..."
        
        # Get additional context
        DURATION_SECONDS=$(( $(date +%s) - $(date -d "${{ github.event.workflow_run.created_at }}" +%s) ))
        DURATION_MINUTES=$(( DURATION_SECONDS / 60 ))
        
        if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "${{ steps.status.outputs.status_emoji }} *${{ steps.status.outputs.workflow_name }}* - ${{ steps.status.outputs.status_text }}",
              "attachments": [
                {
                  "color": "${{ steps.status.outputs.status_color }}",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "${{ steps.status.outputs.status_emoji }} ${{ steps.status.outputs.workflow_name }} - ${{ steps.status.outputs.status_text }}"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ steps.status.outputs.status_message }}"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Repository:*\n${{ github.repository }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Branch:*\n${{ github.event.workflow_run.head_branch }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Duration:*\n'"$DURATION_MINUTES"' minutes"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Triggered by:*\n${{ github.event.workflow_run.triggering_actor.login }}"
                        }
                      ]
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "🏁 Completed at: <!date^$(date +%s)^{date_short_pretty} at {time}|$(date)>"
                        }
                      ]
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "📊 View Full Pipeline"
                          },
                          "url": "${{ steps.status.outputs.run_url }}",
                          "style": "${{ steps.status.outputs.conclusion == 'success' && 'primary' || 'danger' }}"
                        },
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "🔍 View Repository"
                          },
                          "url": "${{ github.server_url }}/${{ github.repository }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }} || echo "❌ Slack notification failed"
        else
          echo "⚠️ SLACK_WEBHOOK_URL not configured"
        fi

  # Job 3: Manual/Custom Notification
  manual-notification:
    runs-on: ubuntu-latest
    name: Manual Notification
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Send custom notification
      run: |
        echo "📢 Sending custom notification..."
        
        # Determine color based on severity
        case "${{ inputs.severity }}" in
          "success")
            COLOR="good"
            EMOJI="✅"
            ;;
          "warning")
            COLOR="warning"
            EMOJI="⚠️"
            ;;
          "error")
            COLOR="danger"
            EMOJI="❌"
            ;;
          *)
            COLOR="#36a64f"
            EMOJI="ℹ️"
            ;;
        esac
        
        if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "'"$EMOJI"' *Manual Notification*",
              "attachments": [
                {
                  "color": "'"$COLOR"'",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "'"$EMOJI"' Manual Notification"
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*Message:* ${{ inputs.message }}"
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Severity:*\n${{ inputs.severity }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Triggered by:*\n${{ github.actor }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Repository:*\n${{ github.repository }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Time:*\n<!date^$(date +%s)^{date_short_pretty} at {time}|$(date)>"
                        }
                      ]
                    }
                  ]
                }
              ]
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }} || echo "❌ Slack notification failed"
        else
          echo "⚠️ SLACK_WEBHOOK_URL not configured"
        fi
